GET http://localhost:8080/api/tables
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMiIsImlhdCI6MTY0MTQ5MzQxOCwiZXhwIjoxNjQxNTM2NjE4fQ.8bU1zdRsnbAah4u0lHOhR2X0lR_g4kZEB7BtmnXa1m8

###

GET http://localhost:8080/api/tables/1


###


POST http://localhost:8080/api/tables
Content-Type: application/json

{
    "_id": 5,
    "posX": 0.546,
    "posY": 0.4215,
    "width": 45,
    "height": 12
}


###

DELETE http://localhost:8080/api/tables/1

###

PATCH http://localhost:8080/api/tables/5
Content-Type: application/json

{
    "posY": 0.421
}

###

GET http://localhost:8080/api/employees


###

POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "_id": 20,
    "password": "aaa",
    "username": "asdfdd",
    "dni": "45454545D",
    "name": "Juan",
    "surname": "Del Río",
    "isAdmin": true
}

###

PATCH http://localhost:8080/api/employees/2
Content-Type: application/json

{
    "id": "5"
}

###

POST http://localhost:8080/api/employees/login
Content-Type: application/json

{
    "username": "minie",
    "password": "aaa"
}