GET http://localhost:8080/api/dishes
authorization: bearer {{token}}
###

POST http://localhost:8080/api/dishes
Content-Type: application/json
authorization: bearer {{token}}

{
    "name": "Hamburguer",
    "ingredients": {
        "pan_hamburguesa": 1,
        "carne_vacuno": 500
    },
    "quantity": 3,
    "type": "Food",
    "price": 15,
    "description": "lsdañjflñkñlasjkfd"
}
###

PATCH http://localhost:8080/api/dishes/1
Content-Type: application/json
authorization: bearer {{token}}

{
    "quantity": 5
}
###

DELETE http://localhost:8080/api/dishes/1
authorization: bearer {{token}}