GET http://localhost:8080/api/tables

###

GET http://localhost:8080/api/tables/1


###


POST http://localhost:8080/api/tables
Content-Type: application/json

{
    "_id": 1,
    "posX": 50.4987,
    "posY": 12.421
}


###

DELETE http://localhost:8080/api/tables/1

###

PATCH http://localhost:8080/api/tables/1
Content-Type: application/json

{
    "posY": 0.421
}