GET http://localhost:8080/api/ingredients
authorization: bearer {{token}}
###

POST http://localhost:8080/api/ingredients
Content-Type: application/json
authorization: bearer {{token}}

{
    "name": "pollo",
    "quantity": 8000
}
###

PATCH http://localhost:8080/api/ingredients/7
Content-Type: application/json
authorization: bearer {{token}}

{
    "name": "azucar"
}
###

DELETE http://localhost:8080/api/ingredients/1
authorization: bearer {{token}}

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json
authorization: bearer {{token}}

{
    "id": 1,
    "name": "pan",
    "quantity": 3.0
}
###