GET http://localhost:8080/api/tables
authorization: bearer {{token}}
###

GET http://localhost:8080/api/tables/6
authorization: bearer {{token}}
###

POST http://localhost:8080/api/tables
Content-Type: application/json
authorization: bearer {{token}}

{
    "posX": 0.546,
    "posY": 0.4215,
    "width": 30,
    "height": 30,
    "actualTicket": "2"
}
###

PATCH http://localhost:8080/api/tables/1
Content-Type: application/json
authorization: bearer {{token}}

{
    "actualTicket": "1"
}
###

DELETE http://localhost:8080/api/tables/4
authorization: bearer {{token}}
