GET http://localhost:8080/api/tables
authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMSIsImlhdCI6MTY0MjY5MDU3NSwiZXhwIjoxNjQyNzMzNzc1fQ.ToYC-tosp_bfUQWtbaM4KlCi75ZudigbSbY1pI4kWrs

###

GET http://localhost:8080/api/tables/1
authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMCIsImlhdCI6MTY0MTgzNzM1OSwiZXhwIjoxNjQxODgwNTU5fQ.6XbxavCZ_-p9zjVGN6ezyP0888jK8F1L_lLssvgsvyU


###


POST http://localhost:8080/api/tables
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMSIsImlhdCI6MTY0MjY5MDU3NSwiZXhwIjoxNjQyNzMzNzc1fQ.ToYC-tosp_bfUQWtbaM4KlCi75ZudigbSbY1pI4kWrs

{
    "posX": 0.546,
    "posY": 0.4215,
    "width": 45,
    "height": 45
}


###

DELETE http://localhost:8080/api/employees/4

###

PATCH http://localhost:8080/api/tables/2
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMSIsImlhdCI6MTY0MjY5MDU3NSwiZXhwIjoxNjQyNzMzNzc1fQ.ToYC-tosp_bfUQWtbaM4KlCi75ZudigbSbY1pI4kWrs

{
    "actualTicket": "1"
}

###

GET http://localhost:8080/api/employees
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQyNzY2NjM0LCJleHAiOjE2NDI4MDk4MzR9.UIYXCVQcVf3RcZCeyRoNE1_xdE-7FJ5CaVnyK7Vy5EU
###

POST http://localhost:8080/api/employees
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMSIsImlhdCI6MTY0MjY5MDU3NSwiZXhwIjoxNjQyNzMzNzc1fQ.ToYC-tosp_bfUQWtbaM4KlCi75ZudigbSbY1pI4kWrs

{
    "password": "12345",
    "username": "matalacabras",
    "name": "mataas",
    "dni": "45454545D",
    "surname": "Nuevo",
    "isAdmin": true
}

###

PATCH http://localhost:8080/api/employees/2
Content-Type: application/json

{
    "username": "juan"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "alvaro",
    "password": "12345"
}

###

GET http://localhost:8080/api/ingredients

###

POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
    "name": "sal",
    "price": 1.0,
    "quantity": 3.0
}

###

PATCH http://localhost:8080/api/ingredients/1
Content-Type: application/json

{
    "name": "azucar"
}

###
DELETE http://localhost:8080/api/ingredients/1

###

GET http://localhost:8080/api/tickets
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQyNzY2NjM0LCJleHAiOjE2NDI4MDk4MzR9.UIYXCVQcVf3RcZCeyRoNE1_xdE-7FJ5CaVnyK7Vy5EU

###

POST http://localhost:8080/api/tickets
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQyNzY2NjM0LCJleHAiOjE2NDI4MDk4MzR9.UIYXCVQcVf3RcZCeyRoNE1_xdE-7FJ5CaVnyK7Vy5EU

{
    "total": 0.00,
    "text": "TICKET",
    "isPaid": false
}

###

PATCH http://localhost:8080/api/tickets/1
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMSIsImlhdCI6MTY0MjY5MDU3NSwiZXhwIjoxNjQyNzMzNzc1fQ.ToYC-tosp_bfUQWtbaM4KlCi75ZudigbSbY1pI4kWrs

{
    "total": 3.00
}



###
DELETE http://localhost:8080/api/tickets/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMSIsImlhdCI6MTY0MjY5MDU3NSwiZXhwIjoxNjQyNzMzNzc1fQ.ToYC-tosp_bfUQWtbaM4KlCi75ZudigbSbY1pI4kWrs
###

GET http://localhost:8080/api/orders/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQyODYzMjk3LCJleHAiOjE2NDI5MDY0OTd9.rlb2pnoGst0qvIOjmm11sHUuoITV4ZBLqA_Dvdc7gWg
###
POST http://localhost:8080/api/orders
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQyNzY2NjM0LCJleHAiOjE2NDI4MDk4MzR9.UIYXCVQcVf3RcZCeyRoNE1_xdE-7FJ5CaVnyK7Vy5EU

{
    "ticket": "1",
    "dish": "Albondigas",
    "hasBeenCoocked": false,
    "hasBeenServed": false,
    "isIncluded": false,
    "description": "",
    "employee": "1"
}

###
PATCH http://localhost:8080/api/orders/1
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQyNzY2NjM0LCJleHAiOjE2NDI4MDk4MzR9.UIYXCVQcVf3RcZCeyRoNE1_xdE-7FJ5CaVnyK7Vy5EU

{
    "ticket": "1",
    "dish": "carne",
    "hasBeenServed": false,
    "employee": "2"
}


###
DELETE http://localhost:8080/api/orders/4
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQyNzY2NjM0LCJleHAiOjE2NDI4MDk4MzR9.UIYXCVQcVf3RcZCeyRoNE1_xdE-7FJ5CaVnyK7Vy5EU

