GET http://localhost:8080/api/tickets
authorization: bearer {{token}}
###

POST http://localhost:8080/api/tickets
Content-Type: application/json
authorization: bearer {{token}}

{
    "total": 0.00,
    "text": "TICKET",
    "isPaid": false,
    "orders": ["1"]
}
###

PATCH http://localhost:8080/api/tickets/1
Content-Type: application/json
authorization: bearer {{token}}

{
    "orders": ["3", "4"]
}
###

DELETE http://localhost:8080/api/tickets/3
authorization: bearer {{token}}