GET http://localhost:8080/api/dishes
authorization: bearer {{token}}
###

POST http://localhost:8080/api/dishes
Content-Type: application/json
authorization: bearer {{token}}

{
    "name": "Hamburguer",
    "ingredientQties": [
        {
            "ingredient": "1",
            "quantity": 200
        },
        {
            "ingredient": "3",
            "quantity": 30
        }
    ],
    "type": "Food",
    "price": 15,
    "description": "Hamburguesa de carne con salsa"
}
###
POST http://localhost:8080/api/dishes
Content-Type: application/json
authorization: bearer {{token}}

{
    "name": "Fanta",
    "ingredientQties": [
        {
            "ingredient": "4",
            "quantity": 200
        }
    ],
    "type": "Drink",
    "price": 2.5,
    "description": "Vaso de Fanta Naranja"
}
###

PATCH http://localhost:8080/api/dishes/1
Content-Type: application/json
authorization: bearer {{token}}

{
    "name": "Hamburguer",
    "ingredientQties": [
        {
            "ingredient": "1",
            "quantity": 200
        },
        {
            "ingredient": "2",
            "quantity": 30
        },
        {
            "ingredient": "3",
            "quantity": 20
        }
    ],
    "type": "Food",
    "price": 15,
    "description": "lsdañjflñkñlasjkfd"
}
###

DELETE http://localhost:8080/api/dishes/2
authorization: bearer {{token}}